Ascendo_web/ascendo_web/game/urls.py
from django.urls import path

from .views import (
    question_view,
    code_view
)

app_name = "game"
urlpatterns = [
    path("next/", view=question_view, name="question"),
    path("code/", view=code_view, name='code')

]

Ascendo_web/ascendo_web/user_profile/urls.py
from django.urls import path

from .views import (
    profile_view
, leader_view
, logout
)

app_name = "user_profile"
urlpatterns = [
    path("profile/", view=profile_view, name="redirect"),
    path("logout/", view=logout, name="logout"),
    path("leaderboard/", view=leader_view, name="lead"),
]

Ascendo_web/ascendo_web/users/urls.py
from django.urls import path

from ascendo_web.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

Ascendo_web/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("", include("ascendo_web.user_profile.urls", namespace="user_profile")),
    path("", include("ascendo_web.game.urls", namespace="game")),
    path(r'nested_admin/', include('nested_admin.urls')),
    # Django Admin, use {% url 'admin:index' %}
    path("admin/", admin.site.urls),
    # User management
    path("users/", include("ascendo_web.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
# urlpatterns += [
#     # API base url
#     path("api/", include("config.api_router")),
#     # DRF auth token
#     path("auth-token/", obtain_auth_token),
# ]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

Ascendo_web/ascendo_web/game/models.py
from django.db import models

from ascendo_web.user_profile.models import Profile


class Question(models.Model):
    question = models.CharField(max_length=500)
    answer = models.CharField(max_length=100)
    is_active = models.BooleanField(default=False)
    image = models.URLField(max_length=500)

    def __str__(self):
        return self.question


class Challenge(models.Model):
    question = models.CharField(max_length=500)
    is_active = models.BooleanField(default=False)
    image = models.URLField(max_length=500)
    answer = models.TextField()

    def __str__(self):
        return self.question


class Response(models.Model):
    CHOICES = ((1, "Correct Answer"), (0, "Wrong Answer"))
    answer = models.TextField()
    create_date = models.DateTimeField()
    status = models.PositiveSmallIntegerField(choices=CHOICES, default=0)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)

Ascendo_web/ascendo_web/rules/models.py
from django.db import models


class Rules(models.Model):
    priority = models.PositiveSmallIntegerField(unique=True)
    rule = models.CharField(max_length=1000)

    def __str__(self):
        return str(self.priority)

    class Meta:
        verbose_name_plural = 'Rules'
        verbose_name = 'Rule'

Ascendo_web/ascendo_web/user_profile/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q

class Profile(models.Model):
    name = models.CharField(max_length=100)
    nick_name = models.CharField(max_length=100)
    contact = models.CharField(max_length=15)
    college = models.CharField(max_length=100)
    language = models.BooleanField(default=False)
    code = models.BooleanField(default=False)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    has_completed = models.BooleanField(default=False)
    last_submission = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Profile"
        ordering = ('-has_completed', 'last_submission', '-code', '-has_completed')

Ascendo_web/ascendo_web/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for ascendo_web."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

Ascendo_web/ascendo_web/game/forms.py
from django import forms

from .models import Response


class ResponseForm(forms.ModelForm):
    class Meta:
        model = Response
        fields = ['answer']


class AnswerForm(forms.Form):
    answer = forms.CharField(max_length=1000)

    def clean(self):
        cleaned_data = super(AnswerForm, self).clean()
        answer = cleaned_data.get('answer')
        if not answer:
            raise forms.ValidationError('You have to write something!')

Ascendo_web/ascendo_web/user_profile/forms.py
from django.forms import ModelForm

from .models import Profile


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'nick_name', 'contact', 'college']

Ascendo_web/ascendo_web/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

Ascendo_web/ascendo_web/game/views.py
from django.shortcuts import render, redirect
from django.utils.timezone import now
from django.views import View

from ascendo_web.rules.models import Rules
from ascendo_web.user_profile.models import Profile
from .brainfuck import evaluate
from .forms import AnswerForm, ResponseForm
from .models import Question, Challenge


class QuestionView(View):
    def get(self, request):
        if request.user.is_authenticated:
            try:
                profile = request.user.profile
            except Profile.DoesNotExist:
                return redirect('user_profile:redirect')

            if profile.has_completed:
                message = "Completed"
                return render(request, 'game/end.html', {"flag": 1, "message": message})

            q = Question.objects.all().first()

            if not q.is_active:
                context = {'code': -1}
                return render(request, 'game/result.html', context)

            if not profile.language:
                context = {'question': q, 'form': AnswerForm()}
                return render(request, 'game/question.html', context)

            if not profile.code:
                return redirect('game:code')


        else:
            return redirect('home')

    def post(self, request):
        if request.user.is_authenticated:
            try:
                profile = request.user.profile
            except Profile.DoesNotExist:
                return redirect('user_profile:redirect')

            if not profile.language:
                context = {'message': "Invalid Answer", 'code': 0}
                form = AnswerForm(request.POST)
                if form.is_valid():
                    answer = form.data.get('answer')
                    question = Question.objects.all().first()
                    if answer:
                        answer = answer.replace(' ', '')
                        if answer.lower() == question.answer:
                            profile.language = True
                            profile.last_submission = now()
                            profile.save()
                            context['message'] = "Congo, You Found the Language"
                            context['code'] = 1
                            return render(request, 'game/result.html', context)
                return render(request, 'game/result.html', context)

        else:
            return redirect('home')


question_view = QuestionView.as_view()


class CodeView(View):
    def get(self, request):
        if request.user.is_authenticated:
            try:
                profile = request.user.profile
            except Profile.DoesNotExist:
                return redirect('user_profile:redirect')

            if profile.has_completed:
                message = "Completed"
                return render(request, 'game/end.html', {"flag": 1, "message": message})

            q = Challenge.objects.all()[0]

            if not q.is_active:
                context = {'code': -1}
                return render(request, 'game/result.html', context)

            if not profile.language:
                return redirect('game:question')

            if not profile.code:
                context = {'code': q, 'form': ResponseForm(), 'comment': Rules.objects.all().last()}
                return render(request, 'game/code.html', context)

        else:
            return redirect('home')

    def post(self, request):
        if request.user.is_authenticated:
            try:
                profile = request.user.profile
            except Profile.DoesNotExist:
                return redirect('user_profile:redirect')

        if not profile.code:
            form = ResponseForm(request.POST)
            if form.is_valid():
                form = form.save(commit=False)
                answer = form.answer
                answer = "\n".join([a.strip() for a in answer.split("\n") if not a.strip().startswith("//")])
                print(answer)
                out, code = evaluate(answer)
                context = {'code': 0}
                if code == -1:
                    context['message'] = "Your Code Has an Input Statement"
                    form.answer = context['message']
                elif code == 1:
                    context['message'] = "Compilation Error"
                    form.answer = context['message']
                elif code == 0:
                    c = Challenge.objects.all()[0]
                    if c.answer.strip() == out.strip():
                        context['message'] = "Completed"
                        context['code'] = 1
                        profile.code = True
                        profile.has_completed = True
                        profile.last_submission = now()
                        profile.save()
                        form.status = 1
                    else:
                        context['message'] = "Wrong Output"
                form.user = request.user.profile
                form.create_date = now()
                form.save()
                return render(request, 'game/result.html', context)


code_view = CodeView.as_view()

Ascendo_web/ascendo_web/rules/views.py
from django.shortcuts import render

# Create your views here.

Ascendo_web/ascendo_web/user_profile/views.py
from django.contrib.auth import logout as log_me_out
from django.shortcuts import render, redirect
from django.utils.timezone import now
from django.views import View
from django.db.models import Q
from ascendo_web.rules.models import Rules
from .forms import ProfileForm
from .models import Profile


# Create your views here.
class ProfileView(View):
    def get(self, request):
        user = request.user
        if user.is_authenticated:
            try:
                profile = user.profile
                return render(request, 'profile/start.html', {'rule': Rules.objects.all().first()})
            except Profile.DoesNotExist:
                form = ProfileForm(initial={'nick_name': user.username})
                return render(request, 'profile/profile.html', {'form': form})
        else:
            return redirect('home')

    def post(self, request):
        user = request.user
        if user.is_authenticated:
            form = ProfileForm(request.POST)
            if form.is_valid():
                form = form.save(commit=False)
                form.user = request.user
                form.last_submission = now()
                form.save()
                return render(request, 'profile/start.html', {'rule': Rules.objects.all().first()})
        else:
            return redirect('home')


profile_view = ProfileView.as_view()


class LeaderView(View):
    def get(self, request):
        context = {'profiles': Profile.objects.filter(Q(code=True) | Q(language=True))}
        if request.user.is_authenticated:
            try:
                profile = request.user.profile
                if profile:
                    if profile.language:
                        context['text'] = "Let's Continue"
                        context['has_started'] = True
                    else:
                        context['text'] = "Let's Start"
                        context['has_started'] = False
            except Profile.DoesNotExist:
                context['text'] = "Let's Start"
                context['has_started'] = False
        else:
            context['text'] = "Let's Start"
            context['has_started'] = False
        return render(request, 'profile/lead.html', context)


leader_view = LeaderView.as_view()


def logout(request):
    log_me_out(request)
    return redirect('home')

Ascendo_web/ascendo_web/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

Ascendo_web/ascendo_web/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

Ascendo_web/ascendo_web/templates/profile/lead.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE HTML>
<html>
<head>
  <title>Ascendo - SC</title>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
  <link rel="stylesheet" href="{% static 'assets/css/main.css' %}"/>
  <noscript>
    <link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}"/>
  </noscript>
</head>
<body class="is-preload">

  {%if request.user.is_authenticated%}
  <div class="signout" >
    <img class="avatar" onclick="show_side_bar(this)" src="{{ request.user.socialaccount_set.all.0.get_avatar_url }}" alt="Not Found" onerror=this.src="{%static 'images/L.jpeg'%}">
  
    
  </div>
  <div id="sidebar" class="sidebar">
    <a>{{request.user.profile.nick_name | title}}</a>
    <a href="{%url 'user_profile:redirect'%}">Rules</a>
    <a class="logout_button" href="{% url 'user_profile:logout'%}">Logout</a>
    
  </div>
  {%endif%}
<div id="wrapper" class="fade-in" onclick="show_side_bar(this)">

  <ul class="circles">
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
</ul>



  <!-- Header -->
  <header id="header">
    <a class="logo">ACM</a>
  </header>

  <!-- Nav -->
  <nav id="nav">
    <ul class="links">
      <li><a href="{% url 'home' %}">Home</a></li>
      {% if has_started %}
        <li><a href="{% url 'game:question' %}">{{ text }}</a></li>
      {% else %}
      {%if request.user.is_authenticated%}
      <li><a href="{%url 'user_profile:redirect' %}" >Let's start</a></li>
      {%else%}
      <li><a href="{% provider_login_url 'google' %}" >Let's start</a></li>
      {%endif%}
      {% endif %}
      <li class="active " color="black"><a href="#">Leader board</a></li>
    </ul>
  </nav>

  <!-- Main -->
  <div id="main">

    <!-- Featured Post -->
    <article class="post hey">
      <header class="major">

        <h2>Table Toppers</h2>
      </header>
      <ol>
        {%if not profiles %}
            <li class="leader-r"><span
            class="name" style="text-align: center;">No one yet</span></li>
            {%endif%}
        {% for profile in profiles %}
          <li class="leader-r"><span
                  class="name"><b> {{ profile.nick_name | title}}</b> </span><span>
                    {%if profile.has_completed%}
                    Completed
                    {%else%}
                    Completed level 1
                    {%endif%}</span></li>
        {% endfor %}
      </ol>


    </article>


  </div>


  <!-- Scripts -->
  <script src="{% static 'assets/js/jquery.min.js' %}"></script>
  <script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
  <script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
  <script src="{% static 'assets/js/browser.min.js' %}"></script>
  <script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
  <script src="{% static 'assets/js/util.js' %}"></script>
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>
</html>

Ascendo_web/ascendo_web/templates/profile/profile.html
{%load static%}
{% load socialaccount %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>Ascendo - SC</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload" >
		{%if request.user.is_authenticated%}
		<div class="signout" >
		  <img class="avatar" onclick="show_side_bar(this)" src="{{ request.user.socialaccount_set.all.0.get_avatar_url }}" alt="Not Found" onerror=this.src="{%static 'images/L.jpeg'%}">
	  
		  
		</div>
		<div id="sidebar" class="sidebar">
			<a>{{request.user.profile.nick_name | title}}</a>
			<a href="{%url 'user_profile:redirect'%}">Rules</a>
			<a class="logout_button" href="{% url 'user_profile:logout'%}">Logout</a>
			
		</div>
		{%endif%}
		<!-- Wrapper -->
			<div id="wrapper"   class="fade-in" onclick="show_side_bar(this)">

				<!-- Intro -->
				
						<div id="wrapper"  class="fade-in">

							<form method="post" class="profile_form">
							{% csrf_token %}
							{{ form }}
							<div style="text-align:center; margin:20px">
								<button class="btn1 large" type="submit">Submit</button>
						</div>
					</div>
					<br><br>
				<!-- Header -->
					

				<!-- Nav -->
					<nav id="nav">
						<ul class="links">
							<li class="active"><a href="{%url 'home' %}">Home</a></li>
							{%if request.user.is_authenticated%}
							<li><a href="{%url 'user_profile:redirect' %}" >Let's start</a></li>
							{%else%}
							<li><a href="{% provider_login_url 'google' %}" >Let's start</a></li>
							{%endif%}
							<li><a href="{%url 'user_profile:lead' %}">Leader board</a></li>
							</ul>
					</nav>

				<!-- Main -->
					<div id="main">

						<!-- Featured Post -->
							<article class="post featured">
								<header class="major">
									
									<p>" First, solve the problem.<br>
									Then, write the code." <br><p style="text-align:right;">- John Johnson</p></p>
								</header>
							
							</article>





			</div>

		<!-- Scripts -->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
    <script src="{% static 'assets/js/browser.min.js' %}"></script>
    <script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
    <script src="{% static 'assets/js/util.js' %}"></script>
	<script src="{% static 'assets/js/main.js' %}"></script>
	<script >

	</script>

	</body>
</html>

Ascendo_web/ascendo_web/templates/profile/start.html
{% load static %}
<!DOCTYPE HTML>

<html>
<head>
  <title>Treasure Hunt</title>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
  <link rel="stylesheet" href="{% static 'assets/css/main.css' %}"/>
  <noscript>
    <link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}"/>
  </noscript>
</head>
<body class="is-preload">
{% if request.user.is_authenticated %}
  <div class="signout">
    <img class="avatar" onclick="show_side_bar(this)" src="{{ request.user.socialaccount_set.all.0.get_avatar_url }}"
         alt="Not Found" onerror=this.src="{% static 'images/L.jpeg' %}">


  </div>
  <div id="sidebar" class="sidebar">
    <a>{{ request.user.profile.nick_name | title }}</a>
    <a href="{% url 'user_profile:redirect' %}">Rules</a>
    <a class="logout_button" href="{% url 'user_profile:logout' %}">Logout</a>

  </div>
{% endif %}
<div id="wrapper" class="fade-in" onclick="show_side_bar(this)">

  <ul class="circles">
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
  </ul>

  <div id="intro">
    <h1>RULES!</h1>
    <p>  {{ rule.rule | safe }}</p>
    

    <a href="{% url 'game:question' %}" class="btn1 icon solid  fas fa-play scrolly">Continue</a>


  </div>
  <!-- Nav -->
  <nav id="nav">
    <ul class="links">
      <li><a href="{% url 'home' %}">Home</a></li>
      <li class="active"><a href="{% url 'user_profile:redirect' %}">Let's start</a></li>
      <li><a href="{% url 'user_profile:lead' %}">Leader board</a></li>
    </ul>
  </nav>


  <div id="main">

    <!-- Featured Post -->
 


  </div>


</div>

<!-- Scripts -->
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
<script src="{% static 'assets/js/browser.min.js' %}"></script>
<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
<script src="{% static 'assets/js/util.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>

</body>
</html>